// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCowaBP77pk7L4XOka7A83ElqAHFlw2yu8',
    appId: '1:432160706126:web:64863842548cb5f8b4bd1f',
    messagingSenderId: '432160706126',
    projectId: 'mrworker-a17a9',
    authDomain: 'mrworker-a17a9.firebaseapp.com',
    storageBucket: 'mrworker-a17a9.appspot.com',
    measurementId: 'G-FBRGXS8D0C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD27GLvoCPPHrFFCbgVVnlOpWHZ6hT4NrU',
    appId: '1:432160706126:android:2ea9e45efc3e9628b4bd1f',
    messagingSenderId: '432160706126',
    projectId: 'mrworker-a17a9',
    storageBucket: 'mrworker-a17a9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBX18FQ9WhnDNbcAE1IWDZLbbYH1yS2I1c',
    appId: '1:432160706126:ios:791176f9b98d0387b4bd1f',
    messagingSenderId: '432160706126',
    projectId: 'mrworker-a17a9',
    storageBucket: 'mrworker-a17a9.appspot.com',
    androidClientId: '432160706126-r9j7qp4h9v60c2vgsa8l83nqpfpp9332.apps.googleusercontent.com',
    iosClientId: '432160706126-q4pa3pap1ljsa9jir788omo39shisij3.apps.googleusercontent.com',
    iosBundleId: 'pk.mrworker.mrworker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBX18FQ9WhnDNbcAE1IWDZLbbYH1yS2I1c',
    appId: '1:432160706126:ios:791176f9b98d0387b4bd1f',
    messagingSenderId: '432160706126',
    projectId: 'mrworker-a17a9',
    storageBucket: 'mrworker-a17a9.appspot.com',
    androidClientId: '432160706126-r9j7qp4h9v60c2vgsa8l83nqpfpp9332.apps.googleusercontent.com',
    iosClientId: '432160706126-q4pa3pap1ljsa9jir788omo39shisij3.apps.googleusercontent.com',
    iosBundleId: 'pk.mrworker.mrworker',
  );
}
